# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'tothemoonapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tothemoonapp
  pod 'Firebase/Core'
  pod 'Firebase/Messaging', '~> 5.3.0'

  target 'tothemoonappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'tothemoonapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tothemoonapp-tvOS

  target 'tothemoonapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
